/** 由文件路径推断 highlight.js 语言 id */
export function languageFromFilePath(path: string): string {
  const name = (path.split("/").pop() || path).toLowerCase();
  const dot = name.lastIndexOf(".");
  const ext = dot >= 0 ? name.slice(dot + 1) : "";

  const map: Record<string, string> = {
    py: "python",
    pyw: "python",
    js: "javascript",
    jsx: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    ts: "typescript",
    tsx: "typescript",
    json: "json",
    md: "markdown",
    mdx: "markdown",
    sql: "sql",
    yaml: "yaml",
    yml: "yaml",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    go: "go",
    rs: "rust",
    java: "java",
    kt: "kotlin",
    kts: "kotlin",
    rb: "ruby",
    php: "php",
    cpp: "cpp",
    cc: "cpp",
    cxx: "cpp",
    h: "cpp",
    hpp: "cpp",
    c: "c",
    cs: "csharp",
    swift: "swift",
    scala: "scala",
    r: "r",
    lua: "lua",
    perl: "perl",
    pl: "perl",
    xml: "xml",
    html: "xml",
    htm: "xml",
    css: "css",
    scss: "scss",
    less: "less",
    dockerfile: "dockerfile",
    makefile: "makefile",
    toml: "ini",
    ini: "ini",
    cfg: "ini",
    conf: "ini",
    vue: "xml",
    tf: "hcl",
    hcl: "hcl",
    graphql: "graphql",
    gql: "graphql",
  };

  if (name === "dockerfile") return "dockerfile";
  if (name === "makefile") return "makefile";
  return map[ext] || "plaintext";
}

export function languageDisplayName(lang: string): string {
  const labels: Record<string, string> = {
    plaintext: "Plain Text",
    python: "Python",
    javascript: "JavaScript",
    typescript: "TypeScript",
    json: "JSON",
    markdown: "Markdown",
    sql: "SQL",
    yaml: "YAML",
    bash: "Shell",
    go: "Go",
    rust: "Rust",
    java: "Java",
    kotlin: "Kotlin",
    ruby: "Ruby",
    php: "PHP",
    cpp: "C++",
    c: "C",
    csharp: "C#",
    swift: "Swift",
    scala: "Scala",
    r: "R",
    lua: "Lua",
    perl: "Perl",
    xml: "HTML",
    css: "CSS",
    scss: "SCSS",
    dockerfile: "Dockerfile",
    makefile: "Makefile",
    ini: "INI",
    hcl: "HCL",
    graphql: "GraphQL",
  };
  return labels[lang] || lang;
}
